#ifndef CPP_WEB_RESULTCODE_H
#define CPP_WEB_RESULTCODE_H

enum class ResultCode: int {
	// Success
	OK,
	CONTINUE,
	// Socket errors
	CREATE_SOCKET_FD_ERROR,
	NON_BLOCK_SET_SOCKET_ERROR,
	BIND_SOCKET_ERROR,
	LISTEN_SOCKET_ERROR,
	SERVER_SOCKET_ALREADY_STARTED,
	NO_NEW_CONNECTIONS,
	NOTHING_TO_READ,
	SOCKET_WAS_CLOSED,

	EMPTY_RESULT,
	PARSER_ERROR
};
#endif //CPP_WEB_RESULTCODE_H
